export { ReactComponent as AddIcon } from './add.svg'
export { ReactComponent as ArrowIcon } from './arrow.svg'
export { ReactComponent as CloseIcon } from './close.svg'
export { ReactComponent as DeleteIcon } from './delete.svg'
export { ReactComponent as DropDownIcon } from './drop-down.svg'
export { ReactComponent as EditIcon } from './edit.svg'
